version: '3.9'

services:
  app:
    image: app
    container_name: '${APP_NAME}'
    restart: on-failure
    build:
      context: $CWD
      dockerfile: ./config/Dockerfile
    ports:
      - '${PORT_SERVER_DEV}:3000'
      - '${PORT_DEV_DEBUG}:3001'
      - '${PORT_SERVER_PROD}:4000'
      - '${PORT_PROD_DEBUG}:4001'
      - '${PORT_HMR}:24678'
      - '${PORT_STORYBOOK}:6006'
    volumes:
      - $CWD:/usr/local/app
      - exclude:/usr/local/app/node_modules
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - uptime:/app/data
    ports:
      - '${PORT_UPTIME}:3001'
  flags_db:
    container_name: flags_db
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: 'flags_db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    expose:
      - 5432
  flags:
    container_name: flags
    image: unleashorg/unleash-server:latest
    ports:
      - '${PORT_FLAGS}:4242'
    environment:
      DATABASE_URL: 'postgres://postgres:unleash@flags_db/postgres'
      DATABASE_SSL: 'false'
    depends_on:
      - flags_db
volumes:
  uptime:
    driver: local
  exclude:
