## @final
##
## NOTE: Do not make changes here without approval from @resist-js/core.

blank_issues_enabled: false
contact_links:
  - name: Read the community guidelines
    about: 'Please make sure you have read the submission guidelines before posting an issue'
    url: https://github.com/resist-js/resist/blob/master/CONTRIBUTING.md#-submitting-an-issue
  - name: Want to start a discussion?
    about: 'Want to start a thread to discuss an idea? Use the discussions feature provided by GitHub.'
    url: https://github.com/nrwl/nx/discussions
  - name: Discord Chat
    url: https://resistjs.dev/chat
    about: Ask questions and discuss with other resist.js users in real time.
