## @final
##
## NOTE: Do not make changes here without approval from @resist-js/core.

name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == '~GITHUB_REPO~'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Talk To Slack
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: resistjs
          status: STARTING
          color: warning
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.11.1'

      - run: npm install -g pnpm
      - run: npm i -g @resistjs/conformances --reporter=silent
      - run: pnpm install --frozen-lockfile=false --reporter=silent
      - run: pnpm run build --filter ./packages
      - run: pnpm run check

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Workflow Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ~APP_NAME~
          status: SUCCESS
          color: good

      - name: Workflow Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ~APP_NAME~
          status: FAILED
          color: danger
