## @final
##
## NOTE: Do not make changes here without approval from @resist-js/core.

name: 👀 Auto Merge

## NOTE: If updating here, also update the corresponding code block in GITHUB_ACTIONS.md as well as @resistjs/go's template.

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'CI'

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot-preview
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
