## @final
##
## NOTE: Do not make changes here without approval from @resist-js/core.

## NOTE: If updating here, also update the corresponding code block in GITHUB_ACTIONS.md as well as @resistjs/go's template.

name: CI

on:
  push:
    branches:
      - master
  pull_request:
env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Talk To Slack
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: resistjs
          status: STARTING
          color: warning

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.11.1'

      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: npm i -g @resistjs/conformances --reporter=silent
      - run: pnpm install --frozen-lockfile=false --reporter=silent
      - run: pnpm run build --filter ./packages
      - run: pnpm run check

      - name: Generate Documentation
        run: pnpm run docs

      - name: Version Documentation
        uses: bobrown101/version-docs@v2.1.20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          doc-location: documentation
          doc-branch: documentation
          commit-msg: 🌻

      - name: Spellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

      - name: Workflow Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: resistjs
          status: SUCCESS
          color: good

      - name: Workflow Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: resistjs
          status: FAILED
          color: danger
