name: CI

on:
  push:
    branches:
      - master
  pull_request:
env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: npm i -g @resistjs/conformances --reporter=silent
      - run: pnpm install --frozen-lockfile=false --reporter=silent
      - run: pnpm run build --filter ./packages
      - run: pnpm run check
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --frozen-lockfile=false --reporter=silent
      - name: Generate docs
        run: pnpm run docs
      - name: Version docs
        uses: bobrown101/version-docs@v2.1.20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          doc-location: documentation
          doc-branch: documentation
          commit-msg: 🌻
